"""Pair every image with its ``-dark`` sibling for the Furo theme switch.

When ``foo.svg`` is embedded and ``foo-dark.svg`` exists next to it, the light
image gets the ``only-light`` class and a copy pointing at the dark file is
inserted with ``only-dark``. Furo shows exactly one of them. Figures are
generated by ``tools/theme_figures.py``; pages keep a single directive.
"""

from __future__ import annotations

import os

from docutils import nodes
from sphinx.application import Sphinx


def pair_dark_images(app: Sphinx, doctree: nodes.document) -> None:
    docname = app.env.docname
    for image in list(doctree.findall(nodes.image)):
        uri = image.get("uri", "")
        if "://" in uri or not uri:
            continue
        stem, extension = os.path.splitext(uri)
        if stem.endswith("-dark"):
            continue
        dark_uri = f"{stem}-dark{extension}"
        _, dark_path = app.env.relfn2path(dark_uri, docname)
        if not os.path.exists(dark_path):
            continue
        dark = image.deepcopy()
        dark["uri"] = dark_uri
        dark["classes"] = [cls for cls in dark.get("classes", []) if cls != "only-light"] + ["only-dark"]
        if "only-light" not in image["classes"]:
            image["classes"].append("only-light")
        image.parent.insert(image.parent.index(image) + 1, dark)


def setup(app: Sphinx) -> dict[str, object]:
    # Priority 400 runs before Sphinx's image collector (500) so the dark
    # copy is registered and copied to the output like any other image.
    app.connect("doctree-read", pair_dark_images, priority=400)
    return {"version": "1", "parallel_read_safe": True, "parallel_write_safe": True}
